version: '3.4'

services:
  backup:
    image: rodriguestiago0/actualbudget-backup:latest
    restart: always
    environment:
    #   RCLONE_REMOTE_NAME: 'ActualBudgetBackup'
    #   RCLONE_REMOTE_DIR: '/ActualBudgetBackup/'
    #   RCLONE_GLOBAL_FLAG: ''
        ACTUAL_BUDGET_URL: 'https://actual.example.com'
        ACTUAL_BUDGET_PASSWORD: ''
        ACTUAL_BUDGET_SYNC_ID: ''
    #   CRON: '0 0 * * *'
    #   BACKUP_FILE_SUFFIX: '%Y%m%d'
    #   BACKUP_KEEP_DAYS: 0
    #   TIMEZONE: 'UTC'
    volumes:
      - actualbudget-rclone-data:/config/
    #   - /path/to/env:/.env
    
volumes:
  actualbudget-rclone-data:
    external: true
    name: actualbudget-rclone-data